// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product.Persistence.Context;

#nullable disable

namespace Product.Persistence.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = new Guid("39ecb0f9-e945-48ea-9880-8400d61cb7c9"),
                            Category = "Phone",
                            Code = "Iphone13White",
                            CreatedDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            ImageURL = "https://productimages.hepsiburada.net/s/189/424-600/110000155170588.jpg/format:webp",
                            IsDeleted = false,
                            Name = "Iphone 13",
                            Price = 34299.0m,
                            UpdatedDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("63870905-124c-41be-9827-a9e026172fb6"),
                            Category = "Phone",
                            Code = "Iphone14White",
                            CreatedDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            ImageURL = "https://productimages.hepsiburada.net/s/376/424-600/110000393677091.jpg/format:webp",
                            IsDeleted = false,
                            Name = "Iphone 14",
                            Price = 38299.0m,
                            UpdatedDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = new Guid("60742fba-3da2-42ec-931a-7e7edd77d3a5"),
                            Category = "Phone",
                            Code = "Iphone15White",
                            CreatedDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            ImageURL = "https://productimages.hepsiburada.net/s/462/424-600/110000498573428.jpg/format:webp",
                            IsDeleted = false,
                            Name = "Iphone 15",
                            Price = 48299.0m,
                            UpdatedDate = new DateTime(2025, 5, 12, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
